### ISSUE TITLE
Fix documentation for configuration of NoHandlerFoundAdviceTrait with Spring Boot >= 2.4.0

### ISSUE THREAD

**Issue by markuswaidhofer** [zalando/problem-spring-web#732]
## Description

In the [readme file, section configuration](https://github.com/zalando/problem-spring-web/blob/main/problem-spring-web/README.md#configuration), it is documented which Spring Boot properties need to be set to make the `NoHandlerFoundAdviceTrait` work:

```
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
```

Starting with Spring Boot 2.4.0, `spring.resources.*` properties were moved to `spring.web.resources.*`: https://github.com/spring-projects/spring-boot/issues/23917

The documentation should be updated to reflect this change (ideally mention different properties based on Spring boot versions).

I ran into this issue when upgrading Spring boot. Moving the property to `spring.web.resources.add-mappings` made `NoHandlerFoundAdviceTrait` work again.

I double checked this with the reference documentation:
* [2.3.x](https://docs.spring.io/spring-boot/docs/2.3.12.RELEASE/reference/htmlsingle/#common-application-properties-web) - property was named `spring.resources.add-mappings`
* [2.4.0](https://docs.spring.io/spring-boot/docs/2.4.0/reference/htmlsingle/#spring.web.resources.add-mappings) - property renamed to `spring.web.resources.add-mappings`

## Possible Fix
Update documentation to mention that Spring boot >= 2.4.0 requires these properties:
```
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
```

I am happy to help here and make a PR if this is fine (first time contributer here 👋).
