### ISSUE TITLE
NoHandlerFoundException is not triggered / missing documentation

### ISSUE THREAD

**Issue by semonte** [zalando/problem-spring-web#79]
First: great library!

I noticed that the NoHandlerFoundAdviceTrait is not triggered without the following config:

```
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
```

This seems to happen because ResourceHttpRequestHandler sends a 404 response. The `throw-exception-if-no-handler-found` is already documented in the `NoHandlerFoundAdviceTrait` class. However, there is no mention about the `add-mappings` which is mandatory as well.
